TESTING = True
SECRET_KEY = "secret"
PERMANENT_SESSION_LIFETIME = 3600
JSONIFY_PRETTYPRINT_REGULAR = True

# SQL settings
# SQLALCHEMY_DATABASE_URI = 'sqlite:///test.db'
# SQLALCHEMY_TRACK_MODIFICATIONS = False